auth_enabled: true

limits_config:
  allow_structured_metadata: true
  otlp_config:
    resource_attributes:
      attributes_config:
        - action: index_label
          attributes:
            - service.name
            - deployment.environment
            - project.name

server:
  http_listen_address: 0.0.0.0
  http_listen_port: 3100
  grpc_server_max_recv_msg_size: 8388608
  grpc_server_max_send_msg_size: 8388608
  http_server_write_timeout: 310s
  http_server_read_timeout: 310s

common:
  path_prefix: /loki
  replication_factor: 1
  compactor_address: ${LOKI_BACKEND_ENDPOINT}
  ring:
    kvstore:
      store: memberlist

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
    cache_ttl: 24h

  aws:
    endpoint: ${MINIO_ENDPOINT}
    s3forcepathstyle: true
    access_key_id: ${MINIO_ROOT_USER}
    secret_access_key: ${MINIO_ROOT_PASSWORD}
    insecure: true
    bucketnames: loki

ruler:
  storage:
    s3:
      endpoint: ${MINIO_ENDPOINT}
      s3forcepathstyle: true
      access_key_id: ${MINIO_ROOT_USER}
      secret_access_key: ${MINIO_ROOT_PASSWORD}
      insecure: true
      bucketnames: loki-ruler

memberlist:
  join_members:
    - loki_backend
    - loki_reader
    - loki_writer
  dead_node_reclaim_time: 30s
  gossip_to_dead_nodes_time: 15s
  left_ingesters_timeout: 30s
  bind_addr:
    - 0.0.0.0
  bind_port: 7946
  gossip_interval: 2s

schema_config:
  configs:
    - from: 2023-01-01
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h

compactor:
  working_directory: /tmp/compactor
