receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  otlphttp/logs:
    endpoint: "${env:LOKI_WRITER_ENDPOINT}/otlp"
    headers:
      X-Scope-OrgID: ${env:LOKI_ORG_ID}

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/logs, debug]
